### PR TITLE
fix: standardize console links

### PR DESCRIPTION
**Pull request by jonas-jonas**
Adds a standardized `<ConsoleLink />` mdx component that can be used to render a Link to a page in the Ory Console. Includes automatic look up of the page's title and navigation section to render 

**Activity** → **Logs & Events** in the [Ory Console](https://console.ory.sh/current/projects/activity/events)

links in the docs.

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by vinckr** [comment]
I dont see the component in this PR though? maybe you didn't commit it or I am blind.

**Comment by jonas-jonas** [comment]
@vinckr [src/components/ConsoleLink/console-link.tsx](https://github.com/ory/docs/pull/1759/files#diff-27b2b74e489968e82450225544732086c36aac6ba65a31d3ecdd7978e97b4769) :)

**Review by vinckr — APPROVED** [review]
Very cool 😎 

IMO ready to merge, if you feel like it add a link to comment in the component in the README here: https://github.com/ory/docs?tab=readme-ov-file#navigating-to-ory-console-pages

**Comment by jonas-jonas** [comment]
@vinckr added.

**Review by zepatrik — APPROVED** [review]

**Pull request merged**
