### PR TITLE
fix: add gpt widget again

### PR DESCRIPTION
**Pull request by vinckr**
Widget now only executes the script file once the HTML document has been fully parsed.
Also added a privacy disclaimer.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by vinckr** [comment]
Screenshot 2023-07-26 at 12 11 33

lighthouse looks good but not sure if the defer works as expected 🤔

**Comment by aeneasr** [comment]
This is desktop lighthouse though, right? You need to check mobile lighthouse as well!

Looks like over 50% of the code bundle is still unused, and it's also loading immediately and not only once we click on the button:

Bildschirmfoto 2023-07-26 um 12 14 23

**Comment by vinckr** [comment]
**desktop**
Lighthouse score with kapa widget
Screenshot 2023-07-28 at 00 27 42
Lighthouse score without kapa widget
Screenshot 2023-07-28 at 00 34 06

**mobile**
Lighthouse score with kapa widget
Screenshot 2023-07-28 at 00 27 10
Lighthouse score without kapa widget
Screenshot 2023-07-28 at 00 33 43

**Review by aeneasr — APPROVED** [review]
It's still dragging down all the scores but I guess it's more useful to us if it's there?

**Comment by vinckr** [comment]
> It's still dragging down all the scores but I guess it's more useful to us if it's there?

Agreed!

Thanks 🙏 

They want to improve it but its not on the immediate roadmap, so at least 2+ months out. 
I will keep on it though.

**Comment by kmherrmann** [comment]
one more thought: could we just disable it on mobile, where it hurts the scores more?

**Pull request merged**
