### PR TITLE
fix: lint documentation

### PR DESCRIPTION
**Pull request by vinckr**
style:
remove [weasel words](https://github.com/errata-ai/write-good/blob/master/write-good/Weasel.yml) (especially "currently"!)
remove [latin abbreviations](https://github.com/errata-ai/Microsoft/blob/2220840b156287eb1090f374dfb9f896bdc79a3e/Microsoft/Foreign.yml)
remove `$` in code examples
lots of markdown linting
adds [contractions](https://github.com/errata-ai/Microsoft/blob/master/Microsoft/Contractions.yml)
remove `the` from Ory Cloud

fixes: 
a ton of smaller mistakes
adds lost jsonnet doc to sidebar
deletes duplicate styleguide

- docs: lint roadmap
- docs: use contractions
- chore: remove duplicate styleguide
- docs: clarify supported databases
- docs: clarify supported databases
- docs: clarify supported databases
- docs: remove some weasel words
- chore: add Jsonnet to spelling
- docs: remove currently and promises
- chore: remove article from ory cloud
- chore: add WebAuthn to spelling
- docs: remove weasel words and other minor fixes
- docs: remove duplicate section
- chore: delete outdated file
- chore: fix markdownlint errors
- fix: add lost document to sidebar
- chore: remove $ and minor fixes
- chore: remove $ and minor fixes
- docs: remove latin abbreviations

### CODE REVIEW

**Comment by vinckr** [comment]
No idea why deploy is failing though 😕 
Locally npm build works fine and also preview.

**Comment by aeneasr** [comment]
> No idea why deploy is failing though 

my fault

**Comment by vinckr** [comment]
Can you take a look @aeneasr ?
Or suggest someone else to review 🙏

**Comment by aeneasr** [comment]
value is still failing though? and there's a merge conflict :D

**Comment by vinckr** [comment]
Yes, there is still a lot of other style-issues to fix, I just did not want to bloat this PR with much more changes. 

Also have to fix some things in the CLI and API docs, but I figured I would do the markdown first and then these parts.

**Comment by aeneasr** [comment]
Ok I see, can you then please disable vale in the CI again?

**Comment by vinckr** [comment]
Currently Vale action is only checking the changed files in a PR. 
So it only fails if there is errors in the files that got changed in that PR. 

What can I do to get this PR merged?

**Comment by aeneasr** [comment]
Ok, got it!

**Pull request merged**
