### PR TITLE
build: remove custom Prettier configuration override for this repository

### PR DESCRIPTION
**Pull request by kevgo**
As discussed in https://github.com/ory/docs/pull/862#issuecomment-1174723879, this PR removes the custom Prettier configuration for this repo. We are now going with the shared Prettier config for all repositories. The only change is that it changes the `printWidth` setting from 130 back to 80 characters.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability.
      If this pull request addresses a security vulnerability,
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by kevgo** [comment]
Please merge this AFTER #897

**Comment by tomekpapiernik** [comment]
Please re-open this PR when you create a branch in this repository. This way we can avoid the branch getting outdated.

**Comment by kevgo** [comment]
I'm not going to do that since this is not how open-source on Github works. Please review this PR and suggest changes or approve. Thanks!

**Review by tomekpapiernik — CHANGES_REQUESTED** [review]
There are over 340 files in this PR while the goal is to simply remove the override. This doesn't look right. Additionally, there seem to be conflicts with the master branch. Can you please clean this up and let me or @vinckr know once it's ready to be re-reviewed? Thank you :)

**Comment by kevgo** [comment]
To quote myself:

> As discussed in https://github.com/ory/docs/pull/862#issuecomment-1174723879, this PR removes the custom Prettier configuration for this repo. We are now going with the shared Prettier config for all repositories. The only change is that it changes the `printWidth` setting from 130 back to 80 characters.

There are over 340 files that had a printWidth of 130 characters and with this change will have a printWidth of 80 characters. I didn't make any changes to the textual content, so all changes are solely reflowing the text to make it 80 characters wide. You don't have to proofread the files, just skim over the changes to get an idea. I'm pretty certain that there are no changes to how it looks on the production website since it was already Prettier-formatted before and Prettier is pretty reliable in reflowing text correctly.

I'm sorry that there are so many files to review. I agree it's not ideal. The good news is that this should be the last PR that changes so many files at once.

**Comment by tomekpapiernik** [comment]
I'm sorry, but I missed the main point of this change altogether. Why change back to 80? It's difficult to work with. Any modern screen will easily accommodate 130 characters. Please leave the line length for this repo unchanged. Thanks!

**Comment by kevgo** [comment]
@tomekpapiernik I made #862 to allow you to override the printWidth from 80 to 130 in this repo to get you comfortable with changing the printWidth from 130 to 80 in the shared Prettier config. In that PR you said: "there's really no need for allowing to override any of the settings - personally I won't be feeling the need to experiment in any way" so I closed that PR.

I had to add the 130-char override temporarily to make it easier (for you and others) to review #888. In this PR I'm removing this temporary override, as agreed with you and requested by you. Now you suddenly change your mind again and want to keep this override and close my PR. You do this after 6 days (!) of apparently not even bothering to understand what this PR even does, and after suggesting more work on my end to make it easier to merge this PR in.

The vast majority of repos on Github use 80 characters width since that works best for most people and their tools. That's a fact. Not everybody uses large high-resolution displays at all times or looks at their text editor in fullscreen all day. As an example, I am working on a 14 inch laptop with a 4k display right now. 14 inch is the most common screen size for laptops. 4k is an above-average resolution. Each of your 130 character lines spans 3 lines in my text editor when I also have the web preview open. This is the setup that we officially recommend to non-technical users to get a WYSIWYG preview of their changes and not feel lost in code. It simply doesn't work well with your formatting on the most common compute hardware (laptops).

image

Even when I put my editor in fullscreen the Markdown source takes up almost the entire screen width. I have never seen a serious book or other print medium that has such long lines. Maybe a vanity project that wants to be different for the sake of being different. Such wide texts are pretty unergonomic in my opinion. One has to almost sway one's head back and forth while reading. It's also a gamble which line to read next after finishing one line, since the beginning of the text is out of my field of vision when I look at the end of that line.

image

Please reopen this PR and help get it merged, as you agreed to do last week.

**Comment by kevgo** [comment]
Here is a Github pull request for a file with 130 characters printWidth in fullscreen. Even at the pretty small font size I'm using here, all lines wrap to the next line.

image

Here is a Github pull request for a file with 80 characters printWidth. None of the lines wrap. It's a much better experience.

image

**Comment by tomekpapiernik** [comment]
I'm sorry, I got confused with everything that's been going on with regards to the Prettier config so far. 

As I'm sure I mentioned multiple times already, 130 characters in line is something that's been agreed upon and it stays for this repo for the time being. If we ever get any complaints about this setting, we shall consider changing it. 

The workflow/workspace arrangement you're describing is just **an** arrangement you chose to use. Personally, I use a different workspace arrangement and 130 characters fit on my screen(s) comfortably in every situation.

---

> This is the setup that we officially recommend to non-technical users to get a WYSIWYG preview of their changes and not feel lost in code.

I'm sorry but I failed to find that in our main repository readme. Could you link to the paragraph that says that this is the recommended setup? 

---
> The vast majority of repos on Github use 80 characters width since that works best for most people and their tools.

Took me 3 seconds to go to the official Docusaurus documentation and find lines as long as 200+ chars. We can agree that Facebook's Docusaurus is a valid example here, right? 
https://github.com/facebook/docusaurus/blob/main/website/docs/guides/creating-pages.md

---

> You do this after 6 days (!)

When you open a PR on Friday in your timezone, at least 3 days pass w/o me having a look. I was OOO on Monday. This makes it 2 days, not 6. 

---

There are a few other things you wrote that I could address but I won't, there's just no point in burning calories to keep this discussion going. If you want to discuss something with me, please arrange a meeting and we'll talk it through - Github discussions have proven to not be the best communication tool in such scenarios. Just know that I don't respond well to the tone you used in this thread and I won't allow you to continue this kind of rhetoric in conversations with me.

**Pull request closed without merging**
