### PR TITLE
fix: update example page

### PR DESCRIPTION
**Pull request by vinckr**
- adds the new vue example
- correct language / title for next.js ect.
- adds 2 missing examples from ory/examples

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
      vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
      maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]

**Comment by tomekpapiernik** [comment]
image
This icon is not loading properly?

**Review by tomekpapiernik — COMMENTED** [review]
Also, do you need the supabase example in 2 sections - official and self-hosted?

**Comment by vinckr** [comment]
Thanks for catching the image @tomekpapiernik !

And yea the supabase example is similar for both instances, but also different in several ways when self-hosting.
so 
https://github.com/ory/examples/tree/master/kratos-keto-oathkeeper-supabase
and
https://github.com/ory/examples/tree/master/supabase-ory-cloud
Maybe we can bring it together sometime.

**Comment by tomekpapiernik** [comment]
Oh, ok! If these are 2 separate entities then that makes perfect sense. 
I wanted to have a look at the preview to make sure that the icon is fixed but I'm getting a `500` from Vercel :(

**Review by aeneasr — APPROVED** [review]

**Pull request merged**
