### PR TITLE
ci: verify formatting

### PR DESCRIPTION
**Pull request by kevgo**
Now that we use Prettier here, let's verify it on CI!

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability.
      If this pull request addresses a security vulnerability,
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by kevgo** [comment]
@tomekpapiernik I'll look for the option to let maintainers update the branch next time. I usually check it. It might not be there since this PR is coming from my private clone. The branch is updated now. Please take another look.

**Comment by tomekpapiernik** [comment]
Sorry, can't merge this now either :/ Can you please work with @vinckr to get it done? I think he works a bit later in the day than I do and this can give you an opportunity to update the branch and then merge it shortly after.

**Comment by vinckr** [comment]
Works for me. 
It would be easier if you just create a branch in this repo in general. I added you to `@ory/documenters` @kevgo, this should give you the required perms.

**Comment by vinckr** [comment]
I dont know why but it says "This branch is out-of-date with the base branch" and the merge button is greyed out. 

Screenshot 2022-07-14 at 08 48 53

**Review by aeneasr — APPROVED** [review]

**Comment by aeneasr** [comment]
Not sure what the problem is here, I'll use my admin rights to resolve this.

**Comment by kevgo** [comment]
@aeneasr thanks for helping with this. I think the option [Require branches to be up to date before merging](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging) in the branch protection rules is enabled. Are there reasons for that? If no, I suggest disabling it for most repos unless we need this option so badly that we are willing to suffer the pains coming from enabling it. 

As long as this option is enabled, we have to sync ALL open PRs each time any other PR is merged, even if there are no merge conflicts. Git Town's `git sync --all` automate this, but it's still super cumbersome and slow to merge PRs this way since we have to sit and wait until CI is green again before we can merge the next PR. Then the entire process repeats. This also puts a lot of pressure on CI.

**Comment by aeneasr** [comment]
Sure, I’ll disable it! For the docs repo it’s not necessary, for code repositories it is though :)

**Pull request merged**
