### PR TITLE
docs: cloud-3950 - Styled docs to match new website theme

### PR DESCRIPTION
**Pull request by fbolton**
## Related Issue or Design Document

Related issue: https://github.com/ory-corp/cloud/issues/3950 - Docs updated to new design

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

This PR modifies the Docusaurus theme and styling to match the new branding and website style:
* Updated logo in the top-left corner to be the same as the new logo from the website
* Change text to use the Google font, Inter 400 (regular weight)
* Using colours: Cyan 500 (for hover), Indigo 900 (for headings), Indigo 300 (for dark theme headings)
* Dark theme has also been updated appropriately.

### CODE REVIEW

**Review by tomekpapiernik — CHANGES_REQUESTED** [review]
This looks great! You've gotta trim the empty space around the logos though. They're pushed into the top left corner of their space and are smaller than they should be when you leave this much blank space around them. LMK if you need help with that.

**Comment by fbolton** [comment]
@tomekpapiernik Well spotted! I probably just need to tweak the attributes in the <svg> tag somehow to adjust the space around the logo. I'll look into it shortly.

**Comment by fbolton** [comment]
@tomekpapiernik I tried rescaling the SVG logos using the viewbox attribute. I'm not sure if this is the most elegant way of doing it, but the alignment looks better now.

**Review by vinckr — APPROVED** [review]
lgtm :)

**Review by tomekpapiernik — APPROVED** [review]

**Pull request merged**
