### PR TITLE
docs: add common upgrade guide for kratos/keto/hydra

### LINKED ISSUE #669: Clarify version tag for access-rules for oathkeeper
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/docs/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/docs/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Currently we have this description of `version` tag

> version (string): The version of Ory Oathkeeper this rule targets with out the +oryOS.<x> appendix. Ory Oathkeeper is able to migrate access rules across versions. If left empty Ory Oathkeeper will assume that the rule is using the same tag as the version that's running.

But actually, it follows semver policy of versioning.

### Reproducing the bug

Visit Access Rule format section on [this page](https://www.ory.sh/docs/oathkeeper/api-access-rules#access-rule-format)

### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

v0.38.23-beta.1

### On which operating system are you observing this issue?

_No response_

### In which environment are you deploying?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by vinckr**
- Add a notice about the changed cookie behaviour - [as pointed out](https://ory-community.slack.com/archives/C012RJ2MQ1H/p1643810037305779?thread_ts=1643793685.271969&cid=C012RJ2MQ1H).
- Improve wording in a few places as bonus ✨ 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Review by aeneasr — CHANGES_REQUESTED** [review]
Please add a guide for `<hydra|keto|kratos> migrate sql` which is what people often forget to run! You can also link to the CLI command in the reference

**Comment by vinckr** [comment]
> Please add a guide for `<hydra|keto|kratos> migrate sql` which is what people often forget to run! You can also link to the CLI command in the reference

IMO it should already be obvious, it is described and linked in the doc? Or is there something I am missing? 

Im adding another sentence to make it crystal clear.

**Comment by vinckr** [comment]
This has PR has changed a bit with latest commit. 
So i added a _common/upgrade import that should work for kratos, hydra and keto. 
We can add the individual differences in the markdown and cover things that are the same for all projects in the imported _common/upgrade. 

Wdyt @aeneasr ?

**Comment by tomekpapiernik** [comment]
The `### Upgrade Tips` section included in every guide presents some really general advice that could be (mostly) applied to the upgrade process for any given piece of software. 

The "meat&potatoes" here is contained in 3 steps: backup -> install new version -> migrate db
This is what's directly related to our software and what's important for people when they're looking at the documentation for a specific piece of software. 

These general remarks/advice/ideas should be treated as blog topics. Documentation is all about the facts and describing how things are and what you can do with them :)

**Comment by gen1us2k** [comment]
> Limit the doc to describing the actual steps that need to be taken to upgrade a component

1. Write down a high-level upgrade plan
   - Who will perform the upgrade?
   - How will the upgrade process look?
   - What components are affected?
1. Devise roll-out plan
   - When is the upgrade due?
   - Will there be an outage?
   - How long will it be?
   - What's your rollback plan?
1. Back up everything!
1. Run a trial upgrade in a local environment. 
   - Update component
   - Run migrations
   - Solve backward incompatibility issues
   - Run tests that everything works fine
   - Try to plan rollout to the staging environment.
1. Run an upgrade on a staging environment.
  - Try to get feedback from users/stakeholders
  - Fix bugs if any
1. Perform tests on staging & prepare the production environment.
   - Write a pre-mortem
1. Run the upgrade on production.

**Comment by gen1us2k** [comment]
During my past experience, we had Kratos & keto running in production and these steps helped me to copy them and write the actual upgrade plan. I found them useful yet it's basically the engineering team's routine. Yet upgrading software is a non-routine thing for most engineering teams and usually, teams upgrade their versions every 3-6 months is the best case because it's a time-consuming operation. Also, I would like to mention that we can have different setups and lots of deployments on various environments like:
- AWS+EKS
- Simple deployment to EC2 instance without docker
- Deployment to EC2 using docker
- Self-hosted k8s cluster
These general steps basically covers everything because actual steps may vary on each environment

**Comment by aeneasr** [comment]
Maybe also add that you probably need to update the SDKs?

**Comment by vinckr** [comment]
I think one of @tomekpapiernik points was (please correct me!) that this kind of checklist:
https://github.com/ory/docs/pull/679#issuecomment-1077718511 is too generic to be included in our documentation. 

Engineers always have to follow this procedure no matter what they upgrade.
As you said
>I found them useful yet it's basically the engineering team's routine.

and

>we can have different setups and lots of deployments on various environments

Honestly I think we cant cover nearly a fraction of the posibilities and it would not be practical either.

For this reason I want to invest **minimal** time into the upgrading documentation and just provide a generic guide. 
In the end the burden for making this better should not be on the Ory team IMO. 
We can create an "OK" document that basically tells you
- backup
- run these comands
- update sdk
- if you run into trouble reach out here.

Anything more just turns this into a giant task, and I think there are many **much** more crucial parts of the documentation - upgrading is something we dont need to concentrate on right now.


So I will now: 

- [ ] declutter the document
- [ ] remove everything too generic
- [ ] remove the components
- [ ] add a notice to update the SDK

and then I will consider this PR done from my side.

**Comment by aeneasr** [comment]
SGTM

**Comment by gen1us2k** [comment]
@vinckr Yep. That makes sense. I would like to suggest these steps as common

1. Check for backward incompatibility changes
2. Check migration guide from x to z version
3. Backup
4. Update SDK
5. Run these commands
6. Run migrations
7. If you run into trouble reach out here

**Comment by tomekpapiernik** [comment]
> Maybe also add that you probably need to update the SDKs?

Things like this, actual steps you must take, commands to run, files to edit. Best practices and stuff - that belongs on blogs ;)

**Review by aeneasr — APPROVED** [review]

**Pull request merged**
