### PR TITLE
Small addition to base64 command

### PR DESCRIPTION
**Pull request by niekcandaele**
## Related Issue or Design Document

This PR adds an argument to the command example of encoding Discord config into base64. This addition outputs the encoded data as a single line, makes it easier to copy paste into the Kratos config.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]
🙏

**Comment by vinckr** [comment]
Did you test this before merging @aeneasr ?

The updated command does not work for me (MacOs)

```
~ ❯ cat something.jsonnet | base64 -w 0                                                                
base64: invalid argument -w
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
```

**Comment by niekcandaele** [comment]
Oh no.. I only tested on Linux. I suspect we have different versions of the base64 command :( 

```
catalysm:~/ $ base64 --version                                                                             
base64 (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Simon Josefsson.

```

**Comment by aeneasr** [comment]
I didn't - my bad. Will revert

**Pull request merged**
