### PR TITLE
docs: corrects kratos example diff

### PR DESCRIPTION
**Pull request by gabeio**
127.0.0.1 should be replaced by accounts.example.com within the example diff.

## Related Issue or Design Document

N/a

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

Just a small change to correct the diff to match the rest of the surrounding diff within the example.

### CODE REVIEW

**Review by vinckr — COMMENTED** [review]
Apologies maybe I did not get something, 
but would this have any effect? 
in both cases both return urls are allowed, right?

**Comment by gabeio** [comment]
> in both cases both return urls are allowed, right?

This seems to be a diff explaining what should be removed and what should be added.

Screen Shot 2022-09-29 at 11 12 29

Above is the current look, notice that everything is shown as red is `127.0.0.1` and everything in green is `accounts.example.com`, I believe the idea is to show people to remove 127.0.0.1 from the example config provided and add their domain instead. So 127.0.0.1 should not be in the allowed return urls.

Sorry for not explaining that better in the original pr.

**Review by vinckr — APPROVED** [review]
I see! 
My bad I did not look too closely at the PR 😅 

Thanks for catching this! 

Was the guide helpful to you?

**Comment by gabeio** [comment]
> Was the guide helpful to you?

Still working through it, but so far yes!

**Pull request merged**
