### PR TITLE
fix: typo in diagram

### PR DESCRIPTION
**Pull request by joshbalfour**
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [] I have added tests that prove my fix is effective or that my feature works.
- [] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by joshbalfour** [comment]
The CLA won't load for me to sign :/
image

**Comment by tomekpapiernik** [comment]
Thanks for your contribution @joshbalfour :) 
I looked at the updated diagram and I see that you updated the initial GET request path from /session to /session**s**, correct? Are there any other changes I should be looking for? 

Unfortunately something got borked in the process and the diagram embed doesn't work the way it's supposed to. You can check that in the preview build [here](https://docs-ardp9jg11-ory.vercel.app/docs/hydra/concepts/logout).

To get this merged, please fix the diagram rendering and then [format the documentation](https://github.com/ory/docs#formatting-documentation). Thanks! :)

Tip: You can get a live docusaurus preview on your machine when you run `npm run start` in the repo. This might help you figure out what's wrong with the diagram quicker.

**Review by tomekpapiernik — CHANGES_REQUESTED** [review]
image

**Review by tomekpapiernik — APPROVED** [review]
Pushed a fix, looks good now. Merging.

**Pull request merged**
