### PR TITLE
feat: add documentation for Salesforce setup

### PR DESCRIPTION
**Pull request by IchordeDionysos**
Add documentation on how to setup Salesforce SSO integrations.

## Related Issue or Design Document

ory/kratos#3984
ory/kratos#4003

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Review by vinckr — APPROVED** [review]
great contribution, thanks!
I haven't tested it out as I dont have Salesforce set up, but I assume that has been done in the /kratos PR.

**Comment by IchordeDionysos** [comment]
image
image
image
image

image
image
image
image

**Comment by IchordeDionysos** [comment]
@vinckr yes, just tested the setup with the documentation again from scratch and found one detail with PKCE and added it to the documentation.

See also the screenshots how it looks.
I wouldn't add them to the documentation but having them here might be useful for someone :)

**Review by vinckr — APPROVED** [review]
Thanks a ton for the addition @IchordeDionysos! 

I wonder if we can make use of the screenshots somehow, but I agree that they probably are outdated soon 🤔

**Comment by IchordeDionysos** [comment]
Hmm maybe we could add this screenshot (as selecting the scopes is a bit strange and to compare the exact OAuth configuration):
image
Maybe we could cut of the basic information as it doesn't bring too much value

And this image as it's less obvious where to get the client ID/secret from:
image

**Review by vinckr — APPROVED** [review]

**Pull request merged**
