### PR TITLE
docs: update webhooks ips

### PR DESCRIPTION
**Pull request by adamwalach**
## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by kmherrmann** [comment]
Do we need to communicate this to all our clients?

**Comment by vinckr** [comment]
Would be good to include in status.ory.sh as maintenance notice as well as a short announcement in the Slack - we can also add a note to the newsletter. 

I am not sure what the impact is - is this relevant if you have some firewall rules around webhooks from Ory Network?

**Comment by adamwalach** [comment]
Yes, I will create a notice in status.ory.sh and send a slack message, the same as we did last time: https://status.ory.sh/maintenance/212371

**Comment by vinckr** [comment]
> Yes, I will create a notice in status.ory.sh and send a slack message, the same as we did last time: https://status.ory.sh/maintenance/212371

perfect, I think we can document that as standard practice whenever we make these types of changes that might affect some customers in production.

**Comment by kmherrmann** [comment]
Maybe we should also send an email about this if it has the potential to break webhooks for those with firewalls?

**Comment by vinckr** [comment]
if you are subscribed to status.ory.sh (which I would recommend to everyone in production) you would get an email I think. 
But yea we can include it in the newsletter tomorrow? Or is there a "maintenance" email channel/audience as well?

**Comment by kmherrmann** [comment]
I think we should create this audience with everyone who is an ory network project member on it.
We can restrict to paid projects to reduce noise.

**Comment by kmherrmann** [comment]
Newsletter is a good idea but also something that’s easy to overlook

**Comment by vinckr** [comment]
Good point. Something like the security newsletter but just for Ory Network? 
Maybe not the right place to discuss it here, but I also need this audience to do the support stuff on Slack. So would go hand in hand to do this in Hubspot i guess.

**Comment by kmherrmann** [comment]
We should have an email list with all Ory Network users (which are members of a project). We can consider only including paid projects or somehow cutting noise by pruning projects that haven't seen activity in 90 days.

This list should not need an opt-out and may only be used for maintenance notifications and potentially sharing information like post mortems. absolutely no marketing, purely necessary information that we expect admins to read. low volume.

**Comment by aeneasr** [comment]
us is now available - merge this?

**Review by kmherrmann — APPROVED** [review]

**Review by vinckr — APPROVED** [review]

**Pull request merged**
