### PR TITLE
chore: add documentation for mapping metadata

### PR DESCRIPTION
**Pull request by thecodeassassin**
Please do not merge before related changes are live.

## Related Issue or Design Document
https://github.com/ory/kratos/pull/2569/commits/e73f9f037ac54a17d8526a7c4001cd7dc052808a
https://github.com/ory/kratos/issues/2552

## Checklist

- [ X ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ X ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ X ] I have read the [security policy](../security/policy).
- [ X ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ X ] I have added tests that prove my fix is effective or that my feature works.
- [ X ] I have added necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Comment by aeneasr** [comment]
Thank you, this looks great! Could you please sign the CLA (just two clicks), then we can merge it right away!

**Comment by thecodeassassin** [comment]
> Thank you, this looks great! Could you please sign the CLA (just two clicks), then we can merge it right away!

Signed :)

**Comment by aeneasr** [comment]
Epic, thanks!

**Pull request merged**
