### PR TITLE
build: Enable Prettier config overrides for this repo

### PR DESCRIPTION
**Pull request by kevgo**
This allows @tomekpapiernik to experiment with different Prettier settings in this repo without having to update https://github.com/ory/prettier-styles each time (which affects the rest of the Ory codebase).

## Related Issue or Design Document

https://github.com/ory/prettier-styles/pull/38#issuecomment-1124959300

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
      vulnerability, I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the
      maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by tomekpapiernik** [comment]
Could you explain what that means in practice, and how this change allows me to experiment?

**Comment by tomekpapiernik** [comment]
For the docs repo I need the formatting to stay away from the indents I choose to make. If you can make that happen then it's okay. If not, let's leave the /docs repo with no forced wrapping.

I don't want to change the current indentation method across the entire documentation set to avoid breaking the formatting on lists. Instead prettier should play nice with the indents that are already in place.

**Comment by kevgo** [comment]
Prettier doesn't break list formatting as long as the Markdown is standards-compliant. I'm happy to help get lists formatted properly if needed. I (strongly) discourage trying to manually format anything. This doesn't scale and leads to endless bikeshed debates.

It always feels nice to take the liberty and format things the way you like. It doesn't feel nice if others take the liberty to format things the way they like. That's why we let tools format everything for us and spend our times on more important things.

**Comment by tomekpapiernik** [comment]
"Formatting" is too big of a word to use. The only thing prettier did was adjust the line length. I didn't see any other benefits. 

What's not "standards-compliant" about pressing `tab` to create an indent that lets docusaurus know that the codeblock/note/list belongs to an ordered/unordered list item? I'm not using any other manual/custom formatting. 

As I said, as long as you create a config that adjusts the line length and doesn't mess with the indents I use to indicate the affiliation of some content to a list item then I'm all in for that! :)

**Comment by kevgo** [comment]
Tabs for indentation are valid Markdown. I'm pretty certain that you guys didn't use tabs when you ran into the [issues that led you to disable Prettier](https://github.com/ory/docs/pull/847#issuecomment-1145682206) because Prettier handles list items indented with tabs correctly ([see for yourself](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgJbwLabRwA6UpxMARgDYRgDWOUAztgCZw76FQlSYDMpAExZccAjADuEEABoQEAA4xs0ZslABDAE46IUgAq6EGlFupStATw0LKOrQzgwAylrxwAMtl7IAZhbMcPaOzm5KTr4A5sgwOgCuISASlHBsHGxeWlDRCVrRcABiEDp4WjCqucggWgkwsgoAFjB41ADqTeLMkWBwrqa42ABuuNY1YMx2IL7BOjCGjtHlAUHJAFbMAB6uMdRwAIoJEPCr1MEKkTpzNeU69GwGUPIgSjq+MO3sME3IABwABku+mC7UcShqbzgc2GcBeAEdjvBFsozLVmABaXjpdIvHRwRHYfGLAorJCBc7JYJ4bBxRJUvaHJFw8lrBQwLSUL5sH7IYTsxzYagxADCEDwZJSzAArC8EsEACqcswUi4gYZJACSUA4sFcYHeKgAgjrXDBrPszsEAL7WoA)).

Code formatting preferences are mostly a matter of what one is used to. When working in a team, there are always people who are used to something else than you are. This leads to endless (and totally unconstructive) debates about meaningless technical details and to disabling valuable automation. All of that is a distraction from what is actually important: creating good content.

In my experience, the only solution is choosing a very opinionated code formatter and make everybody get used to that style. Prettier is also not my formatter of choice (I use a different one on private projects) and I also don't agree with all its decisions. But I'm willing to compromise for the greater good here. The greater good in this case is harmony and productivity, and more time to focus on content.

Tabs for indentation are problematic when editing content via the GitHub UI. When you hit `tab` in a browser text field, it doesn't insert a tab character but jumps to the next input field. That makes community contributions to our docs unnecessarily hard. Tabs display as 8 spaces on many websites and on the command line, causing content to look misaligned. This affects developers inside Ory. Let's therefore go with spaces (which is what Prettier uses).

I wholeheartedly recommend working "with" Prettier (by installing a Prettier plugin that auto-formats the code in your editor every time you save), rather than "fighting" or avoiding it. That makes it an amazing tool that makes your life easier in many ways. It frees you from having to worry about many irrelevant technical details. It makes your code look nicer because everything is aligned and trimmed. It finds bugs for you, like the one mentioned above.

**Comment by tomekpapiernik** [comment]
@kevgo you've made quite a few good points here. I'd love the automated formatting process to be helpful rather than making my work more difficult and time-consuming, so there are a couple of things I'd like to see in the updated setup: 

1. I'd like the formatter not to break the affiliations I make by using indentations. If this requires changing the way it's done then I'm okay with that, but please make sure to let me know how I should adjust my "ways". I also hope you'd handle updating the formatting in existing documents so that they conform to the format accepted by prettier.

2. [Admonitions](https://docusaurus.io/docs/markdown-features/admonitions) cannot be broken in the formatting process. There are two ways they can be done in Docusaurus, but only one of them is accepted by prettier. Please make sure that none of our admonitions are broken after the formatting process runs. 

3. Imported content (such as [this](https://github.com/ory/docs/blob/master/docs/guides/social-signin/auth0.mdx#prevent-having-to-login-after-sign-up) paragraph currently isn't rendered properly if it's indented to make it affiliated with a list item. If possible, I'd like this behavior to be fixed, but I'm not sure if this can be done through formatting.

Does this sound good to you, could you please make sure that these criteria are met?

**Comment by kevgo** [comment]
Sounds good Tom! I'm happy to help migrate the existing documents to Prettier style and am always available for questions. Prettier should support everything we need here, including admonitions. I'm looking forward to working with you on this!

**Comment by piotrmsc** [comment]
so, Amigos, what do we do with that PR @kevgo @tomekpapiernik  ?;-)

**Comment by kevgo** [comment]
Good question @piotrmsc. I opened this ticket just to demo that (and how) one can override the text width per repo, to make everybody comfortable reverting the text width for Markdown back to 80 characters for the shared Prettier config.

I have enabled Prettier and formatted all files in https://github.com/ory/docs/pull/888. Please review and approve this PR, then we can close this one. Thanks!

**Comment by piotrmsc** [comment]
ok, thx for clarification ;-) I leave review for @tomekpapiernik and once #888 is merged please Tom close this one

**Comment by tomekpapiernik** [comment]
@kevgo I'm thinking that once prettier is set up just the way we want it through #888 , there's really no need for allowing to override any of the settings - personally I won't be feeling the need to experiment in any way :) As such, maybe this PR isn't really necessary and we shouldn't add a configuration method that's gonna be completely ignored? WDYT?

**Comment by kevgo** [comment]
Okay, great, that works for me. Thanks for letting us know @tomekpapiernik. I'm going to close this PR then.

**Pull request closed without merging**
