### PR TITLE
feat: login with golang server app

### PR DESCRIPTION
**Pull request by Benehiko**
Example Golang Web app preforming the Login flow

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you! :) Could you please add this app to the CI test pipeline? See:

https://github.com/ory/docs/blob/99e364b920a470606b575c22aad6ff8a79afe8f9/Makefile#L17-L18

https://github.com/ory/docs/blob/master/tests/protect-page-login.spec.ts

https://github.com/ory/docs/blob/master/src/scripts/test.sh

and you probably need to set up go:

https://github.com/ory/docs/blob/99e364b920a470606b575c22aad6ff8a79afe8f9/.github/workflows/playwright.yml#L14-L16

**Comment by aeneasr** [comment]
Otherwise this is perfect, exactly what I imagined :)

**Comment by aeneasr** [comment]
Oh and please name it Go and not Golang :)

**Comment by Benehiko** [comment]
@aeneasr this should be good to go soon :)

**Comment by aeneasr** [comment]
Good job! :)

**Pull request merged**
