### PR TITLE
feat: new sidebar

### PR DESCRIPTION
**Pull request by vinckr**
- **fix: new sidebar**

TODO 

- [x] make sure we really need all those overviews
- [x] Overview Ory Hydra
- [x] Overview Account Experience
- [x] Overview Authentication
- [x] Overview Ory Kratos
- [x] Overview Migrate to Ory
- [x] Overview Licenses
- [x] Add Self-hosting section

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
Should we put guides first? Services is such a broad category

**Comment by vinckr** [comment]
> Should we put guides first? Services is such a broad category

Sorry marked for review but then I changed a bunch of details 😅 
Maybe we can set up a short feedback session once Jonas is back? Or you share some notes already this week via Notion/Slack if you have time.

**Comment by aeneasr** [comment]
makes sense!

**Comment by vinckr** [comment]
continued in https://github.com/ory/docs/pull/1823

**Pull request closed without merging**
