### PR TITLE
docs: styleguide revamp

### PR DESCRIPTION
**Pull request by vinckr**
Redone from https://github.com/ory/docs/pull/674

- docs: remove old styleguide
- docs: style guide to README

### CODE REVIEW

**Comment by aeneasr** [comment]
@vinckr there's some vale issues, can you also please provide a PR in ory/web to fix this?

**Comment by vinckr** [comment]
@aeneasr 
you mean in the CLIdocs? 

I put up a PR to remove the microsoft styles, there is too many rules that we dont want really and it makes the vale action to strict. 
the write-good package is still great I think, 
and we should make some of our own styles, just adding a full set does not seem to work so well - we need to add them bit by bit.

**Comment by aeneasr** [comment]
I mean these redirects:

```
https://www.ory.sh/docs/ecosystem/styleguide https://www.ory.sh/docs/ecosystem/contributing 302!
https://www.ory.sh/docs/ecosystem/styleguide/testing https://www.ory.sh/docs/ecosystem/contributing 302!
https://www.ory.sh/docs/ecosystem/styleguide/templates https://www.ory.sh/docs/ecosystem/contributing 302!
```

you included them in your original PR, but now they are not mentioned anywhere

**Comment by vinckr** [comment]
Oh sorry I forgot to link the PR here: 
https://github.com/ory/web/pull/597

**Pull request merged**
