### PR TITLE
fix: dynamic client registration path in hydra docs

### PR DESCRIPTION
**Pull request by daniel-eichinger-bl**
The dynamic client registration endpoint was specified at /openid/register, but Ory Hydra exposes it at /oauth2/register.

## Related Issue or Design Document
Ory Hydra OpenAPI specification was fixed in this PR: https://github.com/ory/hydra/pull/3141

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments
Will sign the CLA once clarified with my superior.

### CODE REVIEW

**Comment by aeneasr** [comment]
🙏

**Comment by aeneasr** [comment]
@daniel-eichinger-bl sorry, I forgot to check the CLA. Could you please sign it?

**Comment by daniel-eichinger-bl** [comment]
Sure, I just need approval by a manager (he will be back on monday -> then I can sign it). It should be no problem.

**Comment by daniel-eichinger-bl** [comment]
> Sure, I just need approval by a manager (he will be back on monday -> then I can sign it). It should be no problem.

Approval is now done. Sry. for the long time it took -> had to clarify it with our legal department first.

**Pull request merged**
