### PR TITLE
docs: fly.io example config

### PR DESCRIPTION
**Pull request by vinckr**
@tinco Thanks for sharing this! 
Do you think the description is accurate? 

Further would you be up to contribute this to our [new community example repository](https://github.com/ory/examples) - then we can maintain it down the line and give it some more exposure.

In any case thanks for being a part of the Ory community!

### CODE REVIEW

**Comment by aeneasr** [comment]
Should we merge this or do you want to wait for @tinco's feedback?

**Comment by vinckr** [comment]
IMO we can merge this now - I am making some effort this month+ to bring all the content from this page into the ory/examples repo. So we can work backwards from this list.

**Comment by tinco** [comment]
Hi, sorry I'm super busy at work and newborn baby at home, haven't had time to look at it. It's not just for fly.io, it's a 1-container docker deployment, it would basically work in any environment that deploys docker containers.

**Comment by vinckr** [comment]
Dont worry about it! If you dont mind I handle it from here, add it to ory/examples, and will tag you for credit and link to your repo in the example README. This way it will hopefully reach many more people and easier to maintain.

**Pull request merged**
