### PR TITLE
docs: add hsm.key_set_prefix info. jwt ecdsa support correction.

### PR DESCRIPTION
**Pull request by aarmam**
- `hsm.key_set_prefix` documentation update 
- jwt ecdsa support correction

## Related Issue or Design Document

[#3066](https://github.com/ory/hydra/pull/3066)

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Review by aeneasr — APPROVED** [review]
Nice, thanks! Please don't merge yet as we still need to release this!

**Comment by tomekpapiernik** [comment]
Hey @aeneasr , could you please let me know if the information in this PR is correct from the technical point of view? The hydra PR has been merged back in April while this PR was just left hanging.

The conflicts are caused by the switch from 80-character-long lines to 130 chars. so it's nothing serious. 

If you approve it then I can take care of the conflicts and get this merged :)

Thanks!

**Comment by tomekpapiernik** [comment]
> Nice, thanks! Please don't merge yet as we still need to release this!

Got it! Let me know when it's ready to merge. I can get the conflicts sorted out.

**Comment by tomekpapiernik** [comment]
@aeneasr I was just going through the open PRs in this repo and I stumbled on this one here. Is the feature released now? I can work on solving conflicts here and adding this to our docs. :) LMK pls.

**Comment by aarmam** [comment]
> @aeneasr I was just going through the open PRs in this repo and I stumbled on this one here. Is the feature released now? I can work on solving conflicts here and adding this to our docs. :) LMK pls.

Yes this feature is merged https://github.com/ory/hydra/pull/3066

**Review by aeneasr — DISMISSED** [review]

**Comment by aeneasr** [comment]
Could you please resolve the conflicts?

**Comment by tomekpapiernik** [comment]
Conflicts resolved, formatted. Merging :)

**Review by tomekpapiernik — APPROVED** [review]

**Pull request merged**
