### PR TITLE
docs: add logout url example

### PR DESCRIPTION
**Pull request by eghernqvist**
Add example of how to get and link to a logout url in nextjs example.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Comment by tomekpapiernik** [comment]
@Benehiko can you have a look and let me know if this checks out code-wise? Thanks :)

**Review by Benehiko — APPROVED** [review]
Thank you for the contribution :)

I think this looks alright to include @tomekpapiernik

**Review by aeneasr — DISMISSED** [review]

**Comment by aeneasr** [comment]
Awesome, thank you! 🎉 Your contribution makes Ory better :)

**Comment by tomekpapiernik** [comment]
Excellent! 
@eghernqvist one more thing to do before we can get this PR merged - please format the documentation. 
Details: https://github.com/ory/docs#formatting-documentation

Thanks :)

**Comment by eghernqvist** [comment]
@tomekpapiernik ran prettier formatting and pushed now! 👍

**Review by tomekpapiernik — APPROVED** [review]

**Comment by tomekpapiernik** [comment]
Sweet! I'll merge this when the CI passes. Thanks :)

**Pull request merged**
