### PR TITLE
fix: upate rate limits

### PR DESCRIPTION
**Pull request by alnr**

### CODE REVIEW

**Comment by alnr** [comment]
https://docs-p8n0yb8aw-ory.vercel.app/docs/guides/rate-limits

**Review by zepatrik — APPROVED** [review]
Thanks a lot 🙏

**Comment by aeneasr** [comment]
Can you add Enterprise and then mention that we can set the rate limits according to customer demand, they just need to reach out to us - and there link to: https://www.ory.sh/contact

**Comment by alnr** [comment]
> Can you add Enterprise and then mention that we can set the rate limits according to customer demand, they just need to reach out to us - and there link to: https://www.ory.sh/contact

Added a note. Phrasing OK?

**Comment by alnr** [comment]
New preview: https://docs-2q9otx7cn-ory.vercel.app/docs/guides/rate-limits

**Review by zepatrik — APPROVED** [review]

**Pull request merged**
